---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guides
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: guides
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guides
    spec:
      containers:
      - name: guides
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
         - containerPort: 8080
           protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
