---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: guides
  namespace: {{ .Values.namespace }}
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: guides
  port:
    targetPort: 8080
  wildcardPolicy: None
